backend:
  name: github
  repo: maxobaxo/scher-dev-blog
  branch: mother

media_folder: src/images

collections:
  - name: blog
    label: Blog
    folder: src/pages/blog
    create: true
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    preview: true
    publish_mode: 'editorial_workflow'
    fields:
      - { name: title, label: Title }
      - { name: date, label: Date, widget: datetime }
      - { name: layout, label: Layout, widget: hidden, default: blog}
      - { name: path, label: Path }
      - { name: featuredImage, label: Featured Image, widget: image}
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
      
